name: dynamic matrix with inputs
on:
  workflow_dispatch: 
    inputs:
      type:
        description: types
        type: choice
        options:
          - '["1"]'
          - '["2"]'
          - '["3"]'
          - '["1","2"]'
          - '["1","3"]'
          - '["1","2","3"]'
        required: true

jobs:
  create_pr:
    name: Create PR
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    strategy:
      matrix:
        type: ${{ fromJSON(inputs.type) }}
    steps:
      - uses: actions/checkout@v4
      - run: echo "CURRENT_DATE=$(date +'%Y%m')" >> "$GITHUB_ENV"
      - name: Create PR
        run: |
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config user.name "github-actions[bot]"
          git checkout -b $TYPE/add-files-$DATE
          git commit --allow-empty -m "$TYPE/$DATE"
          git push --set-upstream origin $TYPE/add-files-$DATE
          gh pr create --fill
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
          TYPE: ${{ matrix.type }}
          DATE: ${{ inputs.date && inputs.date || env.CURRENT_DATE }}
