on:
  repository_dispatch:
    types: [test_result]

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - env:
          MESSAGE: ${{ join(github.event.client_payload.arrays_of_object, ',') }}
        run: echo $MESSAGE
