on:
  repository_dispatch:
    types: [test_result]

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - env:
          JSON: ${{ fromJson(github.event.client_payload.arrays_of_object) }}
          MESSAGE: ${{ join(fromJson(github.event.client_payload.arrays_of_object), ',') }}
        run: echo $MESSAGE
