on:
  repository_dispatch:
    types: [test_result]

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: Echo key-value pairs
        run: |
          echo '${{ toJson(github.event.client_payload.arrays_of_object) }}' | jq -r '.[] | to_entries[] | "\(.key): \(.value)"' | paste -sd', ' -
